"""challenge

Revision ID: a148b5312e8c
Revises: 06e487573d33
Create Date: 2025-11-03 23:30:58.575133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a148b5312e8c'
down_revision: Union[str, Sequence[str], None] = '06e487573d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('comments', 'update_at')
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('posts', 'update_at')
    op.add_column('tags', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('tags', 'update_at')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('users', 'update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('update_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('users', 'updated_at')
    op.add_column('tags', sa.Column('update_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('tags', 'updated_at')
    op.add_column('posts', sa.Column('update_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('posts', 'updated_at')
    op.add_column('comments', sa.Column('update_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('comments', 'updated_at')
    # ### end Alembic commands ###
